name: first-demo
on:
  push:
    branches: [master]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date + %y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY
